### ISSUE TITLE
Save settings not taking effect!

### ISSUE THREAD

**Issue by ahmedelatab** [EvanHerman/wp-rest-api-controller#17]
When toggling some options in taxonomies on or off, settings are not updated when clicking on save, knowing that I had cleared the cache of the REST API controller as well as the cache of the browser but without result.

**Comment by hermanbritz** [comment]
Did you ever got this problem fixed?

**Comment by ahmedelatab** [comment]
@hermabritz 

Yes!

In the REST API controller page, there is list of endpoints and under each one of them there is a toggle list of metas and their names.

I had noticed that some of these metas have weird names (long string of mixed characters)! When I had turned off these metas, everything worked fine!

**Comment by EvanHerman** [comment]
Whatever the name of the meta keys on the settings page is what is being pulled from the database, and it's possible there is no singular name or other label so it is just pulling the meta key. Glad everything is working fine for you again 👍
