### ISSUE TITLE
Repeating meta fields not returned

### ISSUE THREAD

**Issue by rreeps** [EvanHerman/wp-rest-api-controller#5]
Hi,
  I am a bit of a novice in terms of the API and this plug-in, but I am not seeing my custom meta repeating field returned. I see the section regarding the filter, but is that something I update in the call or do I need to change the plug-in code. My hope is to get all single fields the way I get them now, and the repeating in the array. I only have one repeating field at the moment.
Thanks

**Comment by kpu23** [comment]
Hi @rreeps,

You'll need to use the filter `wp_rest_api_controller_retrieve_meta_single`. 

To keep your current fields the same, we'll scope the filter so we only return an array for the specific field you're referring to. The filter function should look something like this:

```
add_filter( 'wp_rest_api_controller_retrieve_meta_single', 'return_api_response_field_as_array', 10, 3 );

function return_api_response_field_as_array( $single, $renamed_field_name, $original_field_name ) {

	if ( $original_field_name === 'your_meta_field_name' ) {
		return false;
	}

	return $single;
}
```

Replace `your_meta_field_name` with the name of your meta key. In the above example, I am using the original name of your meta key (our plugin allows you to rename the meta key, and if you want your conditional to be based on this then use the `$renamed_field_name` argument.)

Does that make sense?

Let me know,
Kevin.

**Comment by rreeps** [comment]
Thanks Kevin. Where am I adding this to, the controller.php file? My field
name is speakerrepeeatable so we have not renamed anything else you
referred to.


---------------------------------------------
Richard Reeps
Manager, IT Project Management
IEEE
445 Hoes Lane
Piscataway, NJ 08854  USA
+1 732 562 3938, phone
+1 732 562 1727, fax
---------------------------------------------

IEEE. Fostering technological innovation and excellence for the benefit of
humanity.

**Comment by kpu23** [comment]
Add this function to your active theme's functions.php file. Are you familiar with adding filter functions?

**Comment by rreeps** [comment]
OK. I can add them, but if I get stuck I will call in someone more skilled
:-) Thanks

---------------------------------------------
Richard Reeps
Manager, IT Project Management
IEEE
445 Hoes Lane
Piscataway, NJ 08854  USA
+1 732 562 3938, phone
+1 732 562 1727, fax
---------------------------------------------

IEEE. Fostering technological innovation and excellence for the benefit of
humanity.

**Comment by kpu23** [comment]
If your field name is `speakerrepeatable` the function should look exactly like:

```
add_filter( 'wp_rest_api_controller_retrieve_meta_single', 'return_api_response_field_as_array', 10, 3 );

function return_api_response_field_as_array( $single, $renamed_field_name, $original_field_name ) {

	if ( $original_field_name === 'speakerrepeatable' ) {
		return false;
	}

	return $single;
}
```

**Comment by rreeps** [comment]
Right, that is what I added. I am still not getting them back in the meta
though

Here is what I see in the JSON response for the post. I noticed the Array
name is speakerrepeatable, but the field names are actually
speakerrepeatable_socailurl for example. So I tried it with the specific
field name too, no luck.


{

   - id: 1491,
   - date: "2017-07-21T09:51:58",
   - date_gmt: "2017-07-21T13:51:58",
   - guid:
   {
      - rendered: "
      http://ieeemobile.staging.wpengine.com/?post_type=cr3ativspeaker&#038;p=1491
      "
      },
   - modified: "2017-08-11T15:18:58",
   - modified_gmt: "2017-08-11T19:18:58",
   - slug: "ieee-mobile-center-of-excellence-3",
   - type: "cr3ativspeaker",
   - link: "
   http://ieeemobile.staging.wpengine.com/speaker/ieee-mobile-center-of-excellence-3/
   ",
   - title:
   {
      - rendered: "matt"
      },
   - content:
   {
      - rendered: "<p>oh ya gotta be quicker than that.</p> ",
      - protected: false
      },
   - featured_media: 1331,
   - template: "",
   - speakertitle: "Code Kami",
   - speakerurl: "defaulting",
   - speakerurltext: "IEEE",
   - speakerrepeatable:
   [
      -
      [
         -
         {
            - speakerrepeatable_socailimage: "1474",
            - speakerrepeatable_socailurl: "http://www.twitter.com"
            },
         -
         {
            - speakerrepeatable_socailimage: "",
            - speakerrepeatable_socailurl: ""
            }
         ]
      ],
   - speaker_or_exhibitor: "Exhibitor",
   - speakerresource:
   [
      -
      {
         - resource-name: "center",
         - resource-location: "www.google.com"
         },
      -
      {
         - resource-name: "Presentation File 2",
         - resource-location: "www.ieee.org"
         },
      -
      {
         - resource-name: "center",
         - resource-location: "www.google.com"
         },
      -
      {
         - resource-name: "Presentation File 2",
         - resource-location: "www.ieee.org"
         }
      ],


But in the get meta I see this


{
"id": 16344,
"key": "speaker_or_exhibitor",
"value": "Exhibitor",
"_links":
{
"about": [

{
"embeddable": true,
"href": "http://ieeemobile.staging.wpengine.com/wp-json/wp/v2/posts/1491"
}
],
}
}
,

{
"id": 16346,
"key": "speakertitle",
"value": "Code Kami",
"_links":
{
"about": [

{
"embeddable": true,
"href": "http://ieeemobile.staging.wpengine.com/wp-json/wp/v2/posts/1491"
}
],
}
}
,

{
"id": 16347,
"key": "speakerurl",
"value": "defaulting",
"_links":
{
"about": [

{
"embeddable": true,
"href": "http://ieeemobile.staging.wpengine.com/wp-json/wp/v2/posts/1491"
}
],
}
}
,

{
"id": 16348,
"key": "speakerurltext",
"value": "IEEE",
"_links":
{
"about": [

{
"embeddable": true,
"href": "http://ieeemobile.staging.wpengine.com/wp-json/wp/v2/posts/1491"
}
],
}
}
,

{
"id": 16426,
"key": "speakerexhibitor-resource",
"value": "(presentation1)[www.google.com] ",
"_links":
{
"about": [

{
"embeddable": true,
"href": "http://ieeemobile.staging.wpengine.com/wp-json/wp/v2/posts/1491"
}
],
}
}
,

{
"id": 16427,
"key": "speakerexhibitor-resource_1",
"value": "(presentation 2)[www.google.com] ",
"_links":
{
"about": [

{
"embeddable": true,
"href": "http://ieeemobile.staging.wpengine.com/wp-json/wp/v2/posts/1491"
}
],
}
}
,

{
"id": 16476,
"key": "speakerexhibitor-resource_2",
"value": "",
"_links":
{
"about": [

{
"embeddable": true,
"href": "http://ieeemobile.staging.wpengine.com/wp-json/wp/v2/posts/1491"
}
],
}
}
,

{
"id": 16477,
"key": "resource-name_2",
"value": "center",
"_links":
{
"about": [

{
"embeddable": true,
"href": "http://ieeemobile.staging.wpengine.com/wp-json/wp/v2/posts/1491"
}
],
}
}
,

{
"id": 16478,
"key": "resource-location_2",
"value": "www.google.com",
"_links":
{
"about": [

{
"embeddable": true,
"href": "http://ieeemobile.staging.wpengine.com/wp-json/wp/v2/posts/1491"
}
],
}
}
,

{
"id": 16479,
"key": "speakerexhibitor-resource_3",
"value": "",
"_links":
{
"about": [

{
"embeddable": true,
"href": "http://ieeemobile.staging.wpengine.com/wp-json/wp/v2/posts/1491"
}
],
}
}
,

{
"id": 16480,
"key": "resource-name_3",
"value": "Presentation File 2",
"_links":
{
"about": [

{
"embeddable": true,
"href": "http://ieeemobile.staging.wpengine.com/wp-json/wp/v2/posts/1491"
}
],
}
}
,

{
"id": 16481,
"key": "resource-location_3",
"value": "www.ieee.org",
"_links":
{
"about": [

{
"embeddable": true,
"href": "http://ieeemobile.staging.wpengine.com/wp-json/wp/v2/posts/1491"
}
],
}
}
,

{
"id": 16759,
"key": "resource-name",
"value": "center",
"_links":
{
"about": [

{
"embeddable": true,
"href": "http://ieeemobile.staging.wpengine.com/wp-json/wp/v2/posts/1491"
}
],
}
}
,

{
"id": 16760,
"key": "resource-location",
"value": "www.google.com",
"_links":
{
"about": [

{
"embeddable": true,
"href": "http://ieeemobile.staging.wpengine.com/wp-json/wp/v2/posts/1491"
}
],
}
}
,

{
"id": 16761,
"key": "resource-name_1",
"value": "Presentation File 2",
"_links":
{
"about": [

{
"embeddable": true,
"href": "http://ieeemobile.staging.wpengine.com/wp-json/wp/v2/posts/1491"
}
],
}
}
,

{
"id": 16762,
"key": "resource-location_1",
"value": "www.ieee.org",
"_links":
{
"about": [

{
"embeddable": true,
"href": "http://ieeemobile.staging.wpengine.com/wp-json/wp/v2/posts/1491"
}
],
}
}
,

{
"id": 16767,
"key": "speaker_or_exhibitor_email",
"value": "kami@code.com",
"_links":
{
"about": [

{
"embeddable": true,
"href": "http://ieeemobile.staging.wpengine.com/wp-json/wp/v2/posts/1491"
}
],
}
}
],

---------------------------------------------
Richard Reeps
Manager, IT Project Management
IEEE
445 Hoes Lane
Piscataway, NJ 08854  USA
+1 732 562 3938, phone
+1 732 562 1727, fax
---------------------------------------------

IEEE. Fostering technological innovation and excellence for the benefit of
humanity.

**Comment by kpu23** [comment]
Which API endpoint are you hitting? Is it the main post endpoint (via the custom post type slug) or are you accessing a specific meta endpoint? The plugin only controls the main post endpoints (and adds the metadata to them). 

Let me know,
Kevin.

**Comment by rreeps** [comment]
Kevin,
  If I call -
http://ieeemobile.staging.wpengine.com/wp-json/wp/v2/cr3ativspeaker I see
all the speaker posts, and they include the field I am trying to update.

When I try to do the get for meta I hit this:

http://ieeemobile.staging.wpengine.com/wp-json/wp/v2/posts/1520/meta/ Where
1520 is the ID of a speaker content.



---------------------------------------------
Richard Reeps
Manager, IT Project Management
IEEE
445 Hoes Lane
Piscataway, NJ 08854  USA
+1 732 562 3938, phone
+1 732 562 1727, fax
---------------------------------------------

IEEE. Fostering technological innovation and excellence for the benefit of
humanity.

**Comment by kpu23** [comment]
What happens if you just call http://ieeemobile.staging.wpengine.com/wp-json/wp/v2/posts/1520/? Does that return the meta fields correctly?

**Comment by kpu23** [comment]
I'm sorry, use this endpoint:

http://ieeemobile.staging.wpengine.com/wp-json/wp/v2/cr3ativspeaker/1520.

**Comment by rreeps** [comment]
Yes, I see it on that ( see below). but when I update with a post, I can
not post to the name. It is expecting the meta ID, which this does not
return.


   - id: 1520,
   - date: "2017-08-11T21:04:48",
   - date_gmt: "2017-08-12T01:04:48",
   - guid:
   {
      - rendered: "
      http://ieeemobile.staging.wpengine.com/?post_type=cr3ativspeaker&#038;p=1520
      "
      },
   - modified: "2017-08-11T21:04:48",
   - modified_gmt: "2017-08-12T01:04:48",
   - slug: "test-speaker-3",
   - type: "cr3ativspeaker",
   - link: "http://ieeemobile.staging.wpengine.com/speaker/test-speaker-3/",
   - title:
   {
      - rendered: "Test Speaker 3"
      },
   - content:
   {
      - rendered: "<p>another test</p> ",
      - protected: false
      },
   - featured_media: 1449,
   - template: "",
   - speakertitle: "Doctor",
   - speakerurl: "www.md.org",
   - speakerurltext: "Walmart",
   - speakerrepeatable:
   [
      -
      [
         -
         {
            - speakerrepeatable_socailimage: "1405",
            - speakerrepeatable_socailurl: "https://www.facebook.com/ieee"
            }
         ]
      ],


---------------------------------------------
Richard Reeps
Manager, IT Project Management
IEEE
445 Hoes Lane
Piscataway, NJ 08854  USA
+1 732 562 3938, phone
+1 732 562 1727, fax
---------------------------------------------

IEEE. Fostering technological innovation and excellence for the benefit of
humanity.

**Comment by kpu23** [comment]
So when you're hitting the meta endpoint, you're not even seeing the speakerrepeatable field?

**Comment by rreeps** [comment]
Correct. I see everything else, just not that one field.


[

{
"id": 16811,
"key": "resource-name",
"value": "Test 3 File 1",
"_links":
{
"about": [

{
"embeddable": true,
"href": "http://ieeemobile.staging.wpengine.com/wp-json/wp/v2/posts/1520"
}
],
}
}
,

{
"id": 16812,
"key": "resource-location",
"value": "www.dropbox.com",
"_links":
{
"about": [

{
"embeddable": true,
"href": "http://ieeemobile.staging.wpengine.com/wp-json/wp/v2/posts/1520"
}
],
}
}
,

{
"id": 16814,
"key": "speaker_or_exhibitor",
"value": "Speaker",
"_links":
{
"about": [

{
"embeddable": true,
"href": "http://ieeemobile.staging.wpengine.com/wp-json/wp/v2/posts/1520"
}
],
}
}
,

{
"id": 16816,
"key": "speaker_or_exhibitor_email",
"value": "speaker3@test.com",
"_links":
{
"about": [

{
"embeddable": true,
"href": "http://ieeemobile.staging.wpengine.com/wp-json/wp/v2/posts/1520"
}
],
}
}
,

{
"id": 16818,
"key": "speakertitle",
"value": "Doctor",
"_links":
{
"about": [

{
"embeddable": true,
"href": "http://ieeemobile.staging.wpengine.com/wp-json/wp/v2/posts/1520"
}
],
}
}
,

{
"id": 16819,
"key": "speakerurl",
"value": "www.md.org",
"_links":
{
"about": [

{
"embeddable": true,
"href": "http://ieeemobile.staging.wpengine.com/wp-json/wp/v2/posts/1520"
}
],
}
}
,

{
"id": 16820,
"key": "speakerurltext",
"value": "Walmart",
"_links":
{
"about": [

{
"embeddable": true,
"href": "http://ieeemobile.staging.wpengine.com/wp-json/wp/v2/posts/1520"
}
],
}
}
],


---------------------------------------------
Richard Reeps
Manager, IT Project Management
IEEE
445 Hoes Lane
Piscataway, NJ 08854  USA
+1 732 562 3938, phone
+1 732 562 1727, fax
---------------------------------------------

IEEE. Fostering technological innovation and excellence for the benefit of
humanity.

**Comment by kpu23** [comment]
So our plugin does not interact with the `/meta` endpoint at all. I am not sure why your fields aren't showing up but I've experienced a lot of issues with the REST API (I've decided I won't use it until it's fully developed and documented.) I'm not sure if this is an issue on your end or something with the REST API itself; I am able to see my repeating meta fields via  the meta endpoint (in my environment).

I would suggest you ask the WP REST API team for more guidance on why your field isn't showing up on the `/meta` endpoint.

Sorry about that - I am not knowledgeable enough to help with this API issue.

Kevin.

**Comment by rreeps** [comment]
OK. thanks for your help.

---------------------------------------------
Richard Reeps
Manager, IT Project Management
IEEE
445 Hoes Lane
Piscataway, NJ 08854  USA
+1 732 562 3938, phone
+1 732 562 1727, fax
---------------------------------------------

IEEE. Fostering technological innovation and excellence for the benefit of
humanity.
